name: Express Internationalization | GitHub Packages

on:
  push:
    branches: [ github-package ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm i

      - name: Run unit tests
        run: npm run test

      - name: Build package
        run: npm run build

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/Sup3r-Us3r
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN_GITHUB_PACKAGES}}
